dist: xenial
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    # include $HOME/.local/bin for `aws`

before_install:
  - pip install awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - language: java
      jdk: openjdk8
      sudo: true
      stage: test
      addons:
          chrome: stable
      script:
          - chmod 777 drivers/linux/chromedriver
          - mvn clean test
          - pwd
          -./automation-framework-integration/target/TEST-junit-jupiter.xml | tee > ~/$TRAVIS_BUILD_NUMBER/one

    - language: python
      stage: deploy
      python: 3.10-dev
      sudo: true
      script:
          - pip install trcli
          - pwd
          - ls
          - python --version
          - cat ~/$TRAVIS_BUILD_NUMBER/*