dist: xenial
jobs:
  include:
    - language: python
      python: 3.9-dev
      addons:
       chrome: stable
      stage: Run tests and upload results to TestRail
      script:
        - mvn clean compile test
      after_script :
        - pip install trcli
        - trcli -y 
           -h https://testrailsademo.testrail.io/ 
           --project "Travis CI Integration" 
           -u TestUser1@gurock.io 
           -p Test1234@
           parse_junit 
           --title "Automated Tests from travis workflow" 
           --run-description $TRAVIS_JOB_WEB_URL 
           -f "./target/surefire-reports/TEST-TestSuite.xml"
