dist: xenial
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - language: python
      stage: deploy
      python: 3.9-dev
      sudo: true
      script:
          - pip install trcli
          - pwd
          - ls
          - python --version
          - trcli -y -h https://testrail101.testrail.io --project "TestRail CLI code-first" -u gaurav.tyagi@gurock.io -p G00dn1ght29 parse_junit --title "Automated Tests from travis workflow" -f "./sample_reports/TEST-junit-jupiter.xml"

    - language: java
      jdk: openjdk11
      python: "3.11-dev"
      sudo: true
      stage: test
      addons:
        chrome: stable
      script:
        - chmod 777 drivers/linux/chromedriver
        - pwd
        - pip install trcli
        - pwd
        - python --version
        - ls
