dist: xenial
jobs:
  include:
    - language: python
      python: 3.9-dev
      sudo: true
      addons:
        chrome: stable
      stage: deploy
      script:
        - pwd
        - ls
        - chmod 777 drivers/linux/chromedriver
        - mvn test
    - stage: test
      script:
        - pip install trcli
        - python --version
        - trcli -y -h https://testrail101.testrail.io --project "TestRail CLI code-first" -u gaurav.tyagi@gurock.io -p G00dn1ght29 parse_junit --title "Automated Tests from travis workflow" -f "./target/TEST-junit-jupiter.xml"
