jobs:
  include:
    - language: java
      jdk: openjdk8
      sudo: true
      stage: test
      addons:
          chrome: stable
      script:
          - chmod 777 drivers/linux/chromedriver
          - mvn clean test

    - language: python
      stage: deploy
      python: 3.10-dev
      dist: xenial
      sudo: true
      script:
          - pip install trcli
          - pwd
          - ls
          - python --version