jobs:
    include:
        - language: java
          jdk: openjdk8
          sudo: true
          addons:
              chrome: stable
          script:
              - chmod 777 drivers/linux/chromedriver
              - mvn clean test


        - language: python
          python: 3.10-dev
          dist: xenial
          sudo: true
          install:
              - pip install -r requirements.txt
          script:
              - pip install trcli
              - pwd
              - ls
              - python --version
