language: java
# sudo: false
# script: "mvn test"


install:
    - sudo apt-get update
    - sudo apt-get install build-essential
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
    chrome: stable

script:
    - export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/lib/"
    - chmod 777 drivers/linux/chromedriver
    - mvn clean test
