dist: xenial
jobs:
  include:
    - language: python
      python: 3.9-dev
      addons:
        chrome: stable
      stage: Run tests and parse results to TestRail
      before_script:
        - chmod 777 drivers/linux/chromedriver
        - mvn test
      script:
        - pip install trcli
        - trcli -y -h https://testrailsademo.testrail.io --project "Travis CI Integration" -u TestUser1@gurock.io -p Test1234@ parse_junit --title "Automated Tests from travis workflow" -f "./target/TEST-junit-jupiter.xml"
